version: '3.8'

services:
    rabbitmq:
      container_name: rabbitMqContainer
      image: rabbitmq:3-management
      restart: always
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq